name: XCS330
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - cloudpickle
  - cycler
  - h5py
  - lockfile
  - numpy
  - opt-einsum
  - packaging
  - pandas
  - pickleshare
  - python-dateutil
  - requests
  - scikit-learn
  - scipy
  - six
  - scikit-learn=1.1.3
  - tensorboard
  - googledrivedownloader
  - pytest
  - imageio
  - svglib
  - googledrivedownloader
  - pip=22.3.1
  - pip:
    - timeout_decorator
    - "--find-links https://download.pytorch.org/whl/torch_stable.html"
    - torch==1.13.1; sys_platform != "linux" and sys_platform != "win32"
    - torchvision==0.14.1; sys_platform != "linux" and sys_platform != "win32"
    - torch==1.13.1+cpu; sys_platform == "linux" or sys_platform == "win32"
    - torchvision==0.14.1+cpu; sys_platform == "linux" or sys_platform == "win32"